Repository hmcts/ccd-user-profile-api, pull requests merged in 2019-03, with the labels that each got.

#158 [PREVIEW] Remove remote Terraform
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:ccd-user-profile-api-pr-158

#159 RPE-1005 Update java logging, AKS secrets integration
  README.md
  build.gradle
  charts/ccd-user-profile-api/Chart.yaml
  charts/ccd-user-profile-api/requirements.lock
  charts/ccd-user-profile-api/requirements.yaml
  charts/ccd-user-profile-api/values.template.yaml
  config/pmd/rulesets.xml
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  hub.Dockerfile
  src/aat/java/uk/gov/hmcts/ccd/userprofile/tests/BaseTest.java
  src/aat/java/uk/gov/hmcts/ccd/userprofile/tests/helper/S2SHelper.java
  src/main/java/uk/gov/hmcts/ccd/AppInsights.java
  src/main/java/uk/gov/hmcts/ccd/UserProfileApplication.java
  src/main/java/uk/gov/hmcts/ccd/data/jurisdiction/JurisdictionMapper.java
  src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileMapper.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/UserProfile.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/SaveUserProfileOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/UserProfileOperation.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/exception/BadRequestException.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/exception/NotFoundException.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/exception/RestExceptionHandler.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileController.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpoint.java
  src/main/java/uk/gov/hmcts/ccd/repository/PostgreSQLEnumType.java
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/ccd/domain/service/UserProfileOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java
  src/test/resources/integration_tests.properties
Labels: ns:ccd-user-profile-api-pr-159

#161 Suppress code coverage for library level class
  build.gradle
  src/main/java/uk/gov/hmcts/ccd/auth/SecurityConfiguration.java
Labels: ns:ccd-user-profile-api-pr-161

#163 Fix ssl mode after postgres version update
  README.md
  charts/ccd-user-profile-api/values.template.yaml
  docker-compose.yml
  infrastructure/main.tf
  src/main/resources/application.properties
Labels: ns:ccd-user-profile-api-pr-163

#164 Add app insights
  Dockerfile
  docker-compose.yml
  hub.Dockerfile
  lib/AI-Agent.xml
  lib/applicationinsights-agent-2.3.1.jar
  web.config
Labels: ns:ccd-user-profile-api-pr-164

#103 [PREVIEW] Use shared App Insight
  infrastructure/main.tf
  infrastructure/variables.tf
  src/main/resources/application.properties
Labels: ns:ccd-user-profile-api-pr-103, pinned

#165 Add classes for AppInsights
  lib/AI-Agent.xml
Labels: ns:ccd-user-profile-api-pr-165

#166 Bump base image version
  Dockerfile
  hub.Dockerfile
Labels: ns:ccd-user-profile-api-pr-166
