Repository hmcts/ccd-user-profile-api, pull requests merged in 2019-04, with the labels that each got.

#173 RDM-4369: Support reserved characters in userId email address
  src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpoint.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java
  src/test/resources/sql/create_user_profile.sql
Labels: checkpoint, ns:ccd-user-profile-api-pr-173

#181 update Spring Boot version from v2.1.3 to v2.1.4
  build.gradle
Labels: ns:ccd-user-profile-api-pr-181

#182 RDM-4610: CVE-2019-0232 fix
  build.gradle
  infrastructure/main.tf
Labels: checkpoint, ns:ccd-user-profile-api-pr-182
