Repository hmcts/ccd-user-profile-api, pull requests merged in 2019-02, with the labels that each got.

#133 Cleanup: helm pod naming
  charts/ccd-user-profile-api/Chart.yaml
  charts/ccd-user-profile-api/requirements.yaml
  charts/ccd-user-profile-api/values.aat.template.yaml
  charts/ccd-user-profile-api/values.template.yaml
Labels: ns:ccd-user-profile-api-pr-133

#138 Bump Gradle to 4.10.3
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:ccd-user-profile-api-pr-138

#137 Bump use-latest-versions and ben-manes.versions
  build.gradle
Labels: ns:ccd-user-profile-api-pr-137

#140 Add stale bot config
  .github/stale.yml
Labels: ns:ccd-user-profile-api-pr-140

#141 Update Java Helm chart
  charts/ccd-user-profile-api/requirements.yaml
Labels: ns:ccd-user-profile-api-pr-141

#143 disable jpa logging
  src/main/resources/application.properties
Labels: ns:ccd-user-profile-api-pr-143

#142 Update Java Helm chart
  charts/ccd-user-profile-api/Chart.yaml
  charts/ccd-user-profile-api/requirements.lock
Labels: ns:ccd-user-profile-api-pr-142

#148 Use Kubernetes friendly Java image
  Dockerfile
Labels: ns:ccd-user-profile-api-pr-148

#149 Bump Swagger2 from 2.9.0 to 2.9.2
  build.gradle
Labels: ns:ccd-user-profile-api-pr-149

#154 Align Dockerfile and hub.Dockerfile
  Dockerfile
  hub.Dockerfile
Labels: ns:ccd-user-profile-api-pr-154

#156 Upgrade pmd to 6.11.0 to address CVE-2019-7722
  build.gradle
Labels: ns:ccd-user-profile-api-pr-156

#157 Bump checkstyle from 8.12 to 8.18
  build.gradle
Labels: ns:ccd-user-profile-api-pr-157
