Repository hmcts/ccd-user-profile-api, pull requests merged in 2020-06, with the labels that each got.

#277 Release cut 18.1
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  README.md
  build.gradle
  dependency-check-suppressions.xml
  src/aat/resources/features/F-000/S-000.td.json
  src/aat/resources/features/F-097/S-424.td.json
  src/aat/resources/features/F-097/S-467.td.json
Labels: ns:ccd, rel:ccd-user-profile-api-pr-277

#286 Linked S-424 as smoke test
  build.gradle
  dependency-check-suppressions.xml
  src/aat/resources/features/F-097/F-097.feature
Labels: ns:ccd, rel:ccd-user-profile-api-pr-286

#288 fix smoke tests
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-288
