Repository hmcts/ccd-user-profile-api, pull requests merged in 2020-05, with the labels that each got.

#267 RDM-2537 Added the Initial Files for Mutation Testing
  Jenkinsfile_nightly
  [build/reports/pitest/fastermutationtestingoutput]
  build.gradle
Labels: ns:ccd, rel:ccd-user-profile-api-pr-267

#276 Rdm 8176
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-user-profile-api-pr-276

#280 Use befta json excel transformer
  Jenkinsfile_CNP
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-user-profile-api-pr-280

#281 RDM-8393 Update health-spring-boot-starter to 0.0.5
  build.gradle
Labels: ns:ccd, rel:ccd-user-profile-api-pr-281

#285 RDM-XXX Fix develop branch
  Jenkinsfile_CNP
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-user-profile-api-pr-285
