Repository hmcts/ccd-user-profile-api, pull requests merged in 2020-01, with the labels that each got.

#228 add rd_professional_api to allowed services list
  charts/ccd-user-profile-api/values.yaml
Labels: ns:ccd-user-profile-api-pr-228

#229 update chart version after allowed service list change
  build.gradle
  charts/ccd-user-profile-api/Chart.yaml
Labels: ns:ccd-user-profile-api-pr-229

#231 RDM-7116-rm-ase-envir
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:ccd, rel:ccd-user-profile-api-pr-231

#232 Remove unwanted env (ASE) files
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:ccd, rel:ccd-user-profile-api-pr-232

#235 RDM-7289 - Update jackson-databind
  build.gradle
Labels: ns:ccd, rel:ccd-user-profile-api-pr-235

#237 Rdm 1619: Return 404 instead of 400 when profile not found
  build.gradle
  src/main/java/uk/gov/hmcts/ccd/domain/service/FindUserProfileOperation.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java
Labels: ns:ccd, rel:ccd-user-profile-api-pr-237

#240 CVE suppress issue to unblock user-profile pipeline
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-user-profile-api-pr-240

#243 RDM-7406 - Resolve CVE-2020-5398
  build.gradle
Labels: ns:ccd, rel:ccd-user-profile-api-pr-243

#239 RDM-7282 Introduce BEFTA FW
  Jenkinsfile_CNP
  build.gradle
  infrastructure/outputs.tf
  lib/befta-fw-1.0.9-SNAPSHOT.jar
  src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileBeftaMain.java
  src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestAutomationAdapter.java
  src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestDataLoader.java
  src/aat/java/uk/gov/hmcts/ccd/userprofile/tests/AATHelper.java
  src/aat/resources/CCD_BEFTA_JURISDICTION2.xlsx
  src/aat/resources/CCD_BEFTA_JURISDICTION3.xlsx
  src/aat/resources/features/F-000/F-000.feature
  src/aat/resources/features/F-000/S-000.td.json
Labels: ns:ccd, rel:ccd-user-profile-api-pr-239
