Repository hmcts/ccd-user-profile-api, pull requests merged in 2020-12, with the labels that each got.

#346 RDM-10294 Fix All Recent CVEs in All CCD Apps
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-346

#348 temporary suppression
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-348

#349 RDM-10549 Fix CVEs Newly Reported on All 4 Java Apps
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-349

#351 DTSPO-266 Enable self service read only access
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-351

#352 RDM-10616: Bump up befta-fw version to 6.3.0
  build.gradle
  src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestAutomationAdapter.java
  src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestDataLoader.java
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-352
