Repository hmcts/ccd-user-profile-api, pull requests merged in 2020-10, with the labels that each got.

#316 befta fw bump up
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-316

#317 Removing PMD checks
  build.gradle
  config/pmd/ruleset.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-317

#318 Updated run to test instead of integration
  .github/workflows/swagger.yml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-318

#319 test on a branch
  .github/workflows/swagger.yml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-319

#320 Rdm 9551 tf to develop
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-320

#323 Bump up hmcts plugin
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-323

#315 Rdm 9052
  build.gradle
  charts/ccd-user-profile-api/Chart.yaml
  liquibase.gradle
  src/aat/resources/features/F-000/S-000.td.json
  src/aat/resources/features/F-097/S-504.td.json
  src/main/java/uk/gov/hmcts/ccd/AliasWebConfig.java
  src/main/java/uk/gov/hmcts/ccd/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/ccd/auth/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileAuditEntity.java
  src/main/resources/application.properties
  src/main/resources/db/changelog/db.changelog-RDM-9052.xml
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-315

#325 Rdm 9478 fix
  src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileAuditEntity.java
  src/main/resources/db/changelog/db.changelog-RDM-9052.xml
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-325
