Repository hmcts/ccd-user-profile-api, pull requests merged in 2020-04, with the labels that each got.

#273 RDM-8096
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-user-profile-api-pr-273

#274 Rdm 7440
  README.md
  build.gradle
  src/aat/resources/features/F-000/S-000.td.json
  src/aat/resources/features/F-097/S-424.td.json
  src/aat/resources/features/F-097/S-467.td.json
Labels: ns:ccd, rel:ccd-user-profile-api-pr-274

#257 RDM-7843-Stale-PR
  .github/stale.yml
Labels: ns:ccd, rel:ccd-user-profile-api-pr-257

#278 RDM-8277: Resolve CVE's on ccd-user-profile-api Update Spring framwork
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-user-profile-api-pr-278
