Repository hmcts/ccd-user-profile-api, pull requests merged in 2021-08, with the labels that each got.

#417 CCD-231: User profile API to return multiple profiles for a list of Email IDs found in request header
  build.gradle
  src/aat/resources/features/F-098/F-098.base.td.json
  src/aat/resources/features/F-098/F-098.feature
  src/aat/resources/features/F-098/S-098.1.td.json
  src/aat/resources/features/F-098/S-098.2.td.json
  src/aat/resources/features/F-098/S-098.3.td.json
  src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
  src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileEntity.java
  src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepository.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/UserProfileCollection.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/FindUserProfileOperation.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpoint.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/FindUserProfileOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java
  src/test/resources/sql/create_user_profile.sql
  src/test/resources/test.properties
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-417

#421 Suppress CVE-2021-22119
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-421

#419 CCD-1351: Improve performance of /profile endpoint to speed up CCD Logins
  src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepository.java
  src/main/resources/db/migration/V20210727_1351__CCD-1351_add_index_userProfileId.sql
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-419

#425 Resolve CVE-2021-22119 & CVE-2021-28170
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-425

#426 Updated CVE suppression dates to 25/09/2021
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-426
