Repository hmcts/ccd-user-profile-api, pull requests merged in 2021-06, with the labels that each got.

#401 CCD-1268 CVE-2021-22118 in CCD User Profile API
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-401

#403 hldatasetup implementation
  Jenkinsfile_CNP
  build.gradle
  dependency-check-suppressions.xml
  src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/HighLevelDataSetupApp.java
  src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestDataLoader.java
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-403

#404 Reduce auto-skip period to enable 2 uploads in master pipeline
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-404

#405 Changed Jenkins library reference back to master branch
  Jenkinsfile_CNP
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-405

#402 CCD-1268 CVE-2021-22118 in CCD User Profile API
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-402

#406 CCD-1268 CVE-2021-22118 update config imports
  charts/ccd-user-profile-api/Chart.yaml
  charts/ccd-user-profile-api/values.yaml
  src/main/resources/application.properties
  src/main/resources/bootstrap.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-406

#407 befta-fw update to 8.2.0
  Jenkinsfile_CNP
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-407

#408 CCD-1268 CVE-2021-22118 update config imports
  charts/ccd-user-profile-api/values.preview.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-408
