Repository hmcts/ccd-user-profile-api, pull requests merged in 2021-11, with the labels that each got.

#431 CCD-2108: Address CVE-2021-42340
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-431

#429 Update Jenkinsfile_CNP syncBranchesWithMaster
  Jenkinsfile_CNP
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-429

#432 CCD-2142: Address CVE-2021-22096
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-432

#433 CCD-2107: Update CVE suppression dates
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-433
