Repository hmcts/ccd-user-profile-api, pull requests merged in 2021-07, with the labels that each got.

#411 enable HighLevelDataSetup for nightly pipeline
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-411

#413 fix mutation test failure
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-413

#409 fortify scan implementation
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-409

#415 fix for CVE-2021-33037
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-415

#418 CCD-1330: Updated CVE suppression dates to 25/08/2021
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-418
