Repository hmcts/ccd-user-profile-api, pull requests merged in 2021-03, with the labels that each got.

#364 Release cut 21.1
  build.gradle
  charts/ccd-user-profile-api/Chart.yaml
  charts/ccd-user-profile-api/values.yaml
  src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestAutomationAdapter.java
  src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestDataLoader.java
  src/main/java/uk/gov/hmcts/ccd/TransactionConfiguration.java
  src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepository.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/SaveUserProfileOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/UserProfileOperation.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileController.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpoint.java
  src/main/resources/application.properties
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-364

#368 RDM-11234 Upgrade Hikari CP Dependency in All CCD Apps
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-368

#370 RDM-11433 CVE-2021-22112 (User Profile)
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-370

#371 RDM-11089 Postgres11 upgrade clean-up
  dependency-check-suppressions.xml
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-371

#372 RDM-11086 Postgres11 upgrade clean-up
  dependency-check-suppressions.xml
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-372

#373 RDM-11507 CVE-2021-25122 (User Profile)
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-373

#378 RDM-11765 Update CVE Suppress Until Date In All Services
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-378

#380 RDM-11729: Upgrade Befta to 6.13.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-380
