Repository hmcts/ccd-user-profile-api, pull requests merged in 2021-04, with the labels that each got.

#381 RDM-9182: Add exception handler for SQL errors
  Jenkinsfile_CNP
  src/main/java/uk/gov/hmcts/ccd/endpoint/exception/RestExceptionHandler.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/exception/RestExceptionHandlerTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-381

#383 RDM-9182: Use Jupiter instead of standard JUnit annotation
  src/test/java/uk/gov/hmcts/ccd/endpoint/exception/RestExceptionHandlerTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-383

#385 RDM-11881 - Use jitpack for befta dependency
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-385

#386 Create scheduled-dummy-commit.yml
  .github/workflows/scheduled-dummy-commit.yml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-386

#387 Update scheduled-dummy-commit.yml try force
  .github/workflows/scheduled-dummy-commit.yml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-387

#390 RDM-12131 Extend Expiry Dates of All CVE Suppressions in CCD Repos
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-390
