Repository hmcts/ccd-user-profile-api, pull requests merged in 2021-12, with the labels that each got.

#435 CCD-2312: Temporarily disable Fortify Scan in nightly build
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-435

#436 update log4j
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-436

#437 CCD-2351: Update log4j version to 2.16.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-437

#438 CCD-2231: Updated CVE suppression dates
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-438

#439 CCD-2374: Update log4j version to 2.17.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-439
