Repository hmcts/ccd-user-profile-api, pull requests merged in 2021-05, with the labels that each got.

#377 RDM-9765
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-377

#393 Upgrade to Postgres 11
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-393

#395 Use correct product for postgres v11
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-395

#394 Upgrade to Postgres 11
  src/main/resources/bootstrap.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-394

#391 RDM-9847 Migrate from Liquibase to Flyway - User Profile
  Jenkinsfile_CNP
  build.gradle
  charts/ccd-user-profile-api/Chart.yaml
  charts/ccd-user-profile-api/values.preview.template.yaml
  charts/ccd-user-profile-api/values.yaml
  dependency-check-suppressions.xml
  liquibase.gradle
  src/main/resources/application.properties
  src/main/resources/db/changelog/db.changelog-0.0.1.xml
  src/main/resources/db/changelog/db.changelog-0.0.2.xml
  src/main/resources/db/changelog/db.changelog-RDM-10028.xml
  src/main/resources/db/changelog/db.changelog-RDM-2761-UserProfileAuditTable.xml
  src/main/resources/db/changelog/db.changelog-RDM-3853.xml
  src/main/resources/db/changelog/db.changelog-RDM-5499.xml
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/db/migration/V0001__Base_version.sql
  src/main/resources/liquibase.properties
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-391

#365 RDM-11092/11093 - Cleanup DB migration
  charts/ccd-user-profile-api/values.aat.template.yaml
  dependency-check-suppressions.xml
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: Do NOT Merge, ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-365

#400 CCD-1230 CVE-2021-22112 (CCD User Profile API)
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-400
