Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-04, with the labels that each got.

#458 --Adding the Suppression for Spring Beans jar. Temporary fix.
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-458

#457 spring framework version update to 5.3.18
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-457

#460 New Dates
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-460

#459 jackson.version update for CVE-2020-36518
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-459
