Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-07, with the labels that each got.

#483 CCD-3434 Upgrade Java, postgresql and redis configurations
  charts/ccd-user-profile-api/Chart.yaml
  charts/ccd-user-profile-api/values.preview.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-483

#455 CCD-2496 Update all repos with multi arch base images
  Dockerfile
  acb.tpl.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-455

#482 CCD-965: Remove Temporary Sonar Exclusions ccd-user-profile-api
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-482

#485 CCD-3536: CVE-2022-31569 suppress
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-485

#486 CCD-3561 Upgrade Java and Node JS versions in chart for all the respe…
  charts/ccd-user-profile-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-486

#484 CCD-3504 Upgrade to latest java plugin - java plugin upgraded to 0.12…
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-484
