Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-09, with the labels that each got.

#495 Suppress CVE-2022-25857 in suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-495

#494 CCD-3577 Cleanup CVE Suppressions
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-494

#496 CCD-3432 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-496

#499 CCD-3682 Suppressions for snakeyaml CVE-2022-38751 CVE-2022-38750 CVE…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-499

#498 CCD-3672: Fix preview deploy issues
  Jenkinsfile_CNP
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-498

#487 CCD-3539: Stop running Nightly builds on weekends
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-487

#489 Remove Version Number
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-489

#502 CCD-3736: Suppress CVE-2022-38752
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-502
