Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-12, with the labels that each got.

#514 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-514

#516 CCD-4047-Fix-CVE-2022-41946
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-516

#518 CCD-4017 Upgrade base charts for Jenkins enhancements - bumped java v…
  charts/ccd-user-profile-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-518

#517 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-517
