Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-06, with the labels that each got.

#473 CCD-3297: Added junit formatter to smoke and functional test tasks
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-473

#474 Revert "CCD-3297: Added junit formatter to smoke and functional test tasks"
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-474

#475 CCD-3297: Added junit formatter to smoke and functional test tasks
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-475

#476 CCD-3376 update java chart version
  charts/ccd-user-profile-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-476

#471 CCD-3200 Fortify Issue 24259069 - Dockerfile Misconfiguration: Defaul…
  docker/database/Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-471

#477 CCD-3387 Remove CVE Suppress Until Date from All Services
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-477
