Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-01, with the labels that each got.

#442 Amend suppression date by 1 month
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-442

#440 CCD-2378: Re-enable Fortify scan
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-440

#443 Update to build.gradle
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-443
