Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-11, with the labels that each got.

#508 CCD-3917 CVE-2022-31690, CVE-2022-31690 CCD-3918 CVE-2022-42252 Suppr…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-508

#506 CCD-3802 Update to fortify-client version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-506

#510 CCD-3918 CVE-2022-42252
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-510

#511 CCD-3917 Spring Security Upgrade
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-511

#507 CCD-3533 Add suppressCves task
  .github/workflows/dependency-check.yml
  build.gradle
  dependency-check-suppressions.xml
  gradle/suppress.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-507

#512 CCD-3916 Update Github actions in workflow - dev branch added and on …
  .github/workflows/scheduled-dummy-commit.yml
  .github/workflows/swagger.yml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-512
