Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-10, with the labels that each got.

#500 CCD 3658 suppress CVE CVE 2022 25857 - fix
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-500

#504 Added CVE suppression
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-504

#503 CCD-3773 Conditionally cleanup helm releases on PRs
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-503, keep-helm

#505 CCD-3776 CVE-2022-42003 and CVE-2022-42004 jackson upgraded to 2.14.0…
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-505
