Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-08, with the labels that each got.

#491 CCD-3606: Temporarily suppress CVE-2022-31197
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-491

#492 CCD-3606: CVE-2022-31197 - Upgraded org.postgresql to 42.4.1 and removed temp suppression
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-492

#493 Add backstage configuration file
  catalog-info.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-493
