Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-03, with the labels that each got.

#452 update test definition version to 7.13.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-452

#456 cve activities
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-456

#450 CWE 862
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-450
