Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-05, with the labels that each got.

#463 CCD-3109 Updated spring-framework.version to 5.3.19 and removed suppression for CVE-2022-22968
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-463

#465 suppression of CVE-2016-1000027 and until date extension for current …
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-465

#466 suppression of CVE-2022-29885
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-466

#468 suppression of CVE-2022-22970,CVE-2022-22971
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-468

#467 CVE-2022-29885: ccd-user-profile-api fix
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-467

#464 CCD-3088 Remove redundant entries from suppression files
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-464

#470 Removed suppressions and updated spring-framework.version to 5.3.20
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-470
