Repository hmcts/ccd-user-profile-api, pull requests merged in 2022-02, with the labels that each got.

#441 CCD-2431: ccd-user-profile-api Validate the scope of transactions i…
  src/main/java/uk/gov/hmcts/ccd/data/jurisdiction/JurisdictionRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileAuditEntityRepository.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/CreateUserProfileOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/DeleteUserProfileJurisdictionOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/FindAllUserProfilesOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/FindUserProfileOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/SaveUserProfileOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/UserProfileOperation.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileController.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpoint.java
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-441

#444 CCD-2543: Ignore Fortify scan results
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-444

#445 CCD-2590: Suppress CVE pending investigation
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-445

#446 CVE fixes
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-446

#447 CWE-862 Suppression
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-447

#448 helm chart update
  charts/ccd-user-profile-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-448

#451 helm chart update
  charts/ccd-user-profile-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-451
