Repository hmcts/ccd-user-profile-api, pull requests merged in 2023-10, with the labels that each got.

#562 CCD-4845: renovate config
  .github/renovate.json
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-562

#566 Disabled demo environment synchronisation within Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-566

#567 CCD-4955 -- Postgres v15 update to Flex DB
  Jenkinsfile_CNP
  dependency-check-suppressions.xml
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, add-or-update, rel:ccd-user-profile-api-pr-567

#547 CCD-4737 : Fix CVE-2023-28709 (removed suppression as no longer required)
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-547
