Repository hmcts/ccd-user-profile-api, pull requests merged in 2023-11, with the labels that each got.

#572 Added demo environment to branchesToSync array
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-572

#573 Merge demo to master
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, add-or-update, rel:ccd-user-profile-api-pr-573

#574 Add subnet_suffix for expanded subnet in Terraform config
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
Labels: ns:ccd, prd:ccd, add-or-update, rel:ccd-user-profile-api-pr-574

#568 CCD-4970 : Fix CVE-2020-8908
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-568

#575 Updating to v15 flexible server reference
  charts/ccd-user-profile-api/values.aat.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-575
