Repository hmcts/ccd-user-profile-api, pull requests merged in 2023-02, with the labels that each got.

#529 CCD-4046
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-529

#525 CCD-4233 CVE-2022-45143 Upgrade Tomcat to 9.0.69, suppression removed
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-525

#532 CCD-4267
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-532

#531 Ccd 4317 upgrade base charts
  charts/ccd-user-profile-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-531
