Repository hmcts/ccd-user-profile-api, pull requests merged in 2023-09, with the labels that each got.

#558 added logging
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-558

#559 revert reporting library to match data store
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-559

#561 Archive cucumber error reports
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-561

#563 CCD-3710 Update applicationinsights.json/fix build
  .github/renovate.json
  Jenkinsfile_CNP
  lib/applicationinsights.json
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-563
