Repository hmcts/ccd-user-profile-api, pull requests merged in 2023-08, with the labels that each got.

#553 Update build.gradle task Functional
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-553

#554 Update build.gradle task functional
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-554

#555 Update build.gradle Functional Task
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-555

#556 Update build.gradle
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-556
