Repository hmcts/ccd-user-profile-api, pull requests merged in 2023-03, with the labels that each got.

#533 CCD-4396 : Update .terraform-version
  infrastructure/.terraform-version
Labels: ns:ccd, prd:ccd, no-changes, rel:ccd-user-profile-api-pr-533

#534 update befta-fw version to 8.7.11
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-534

#523 CCD-1316
  build.gradle
  src/aat/resources/features/F-000/S-000.td.json
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-523

#535 CCD-4398 Upgrade dependencies to resolve CVE-2023-24998
  build.gradle
  charts/ccd-user-profile-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-535

#537 CCD-4476 : replaced reform-api-docs with cnp-api-docs
  .github/workflows/swagger.yml
  README.md
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-537
