Repository hmcts/ccd-user-profile-api, pull requests merged in 2023-01, with the labels that each got.

#520 CCD-4157: Suppress CVE
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-520

#521 CCD-4163 Bump rse-gradle-java-plugin version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-521

#524 Update Chart.yaml
  charts/ccd-user-profile-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-524

#528 CCD-4283 Bump rse-gradle plugin to add dependency-check v8.0.2
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-528
