Repository hmcts/ccd-user-profile-api, pull requests merged in 2024-04, with the labels that each got.

#588 5197 Excluded H2 transitive dependency to resolve CVE
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-588

#581 CCD-5160 : Fix CVE-2023-35116 : bumped jackson.version to 2.16.0
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-581

#592 Bump java chart due to pipeline failures
  charts/ccd-user-profile-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-592

#583 Version bumped to resolve CVE
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-583

#596 autoscaling set to false until CCD-5163 is progressed.
  charts/ccd-user-profile-api/Chart.yaml
  charts/ccd-user-profile-api/values.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-596

#585 CVE-2023-33202 : Fix org.bouncycastle vulnerable version
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-585
