Repository hmcts/ccd-user-profile-api, pull requests merged in 2024-05, with the labels that each got.

#594 CCD-5198 Raised Spring version to resolve CVE
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-594

#593 Remove unnecessary runtime dependencies
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-593

#600 CCD-5273 Update values.yaml point to v15 d/b
  charts/ccd-user-profile-api/Chart.yaml
  charts/ccd-user-profile-api/values.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-600

#591 CCD-5201 Upgraded spring security to 6.1.5 as this is the last version that do…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-591
