Repository hmcts/ccd-user-profile-api, pull requests merged in 2024-03, with the labels that each got.

#540 Ccd 4412 deprecated internal urls
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-540

#587 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-587

#582 Fix CVE-2023-41080 : Update org.apache.tomcat.embed to 10.1.13
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-582

#590 Add stalebot
  .github/workflows/stale.yml
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-590
