Repository hmcts/ccd-user-profile-api, pull requests merged in 2025-04, with the labels that each got.

#626 CME-482: Disable sync to ITHC for database monitoring testing
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-user-profile-api-pr-626

#627 CME-482: Add database monitoring
  Jenkinsfile_CNP
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, aat/add-or-update, prod/add-or-update, rel:ccd-user-profile-api-pr-627

#630 CCD-6287 - Remove plpgsql extension from PSQL TF
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, aat/add-or-update, prod/no-changes, rel:ccd-user-profile-api-pr-630
